### ISSUE TITLE
pirna annotation

### ISSUE THREAD

**Issue by QingLuo90** [junchaoshi/sports1.1#11]
Hi there,

The final output of all piRNAs are labeled the same as "piRNA". Is there a way to include the piRNA id?

**Comment by junchaoshi** [comment]
Hi,

The id for piRNA somehow is meaningless. Sometimes the ids are contradictive with each other among different databases. In this case, you can just name them using unique ids in your work.

**Comment by QingLuo90** [comment]
Hi Junchao,

Thanks for replying promptly. Since the piRNA database has a lot of annotation info which is using the same id. I think things would be easier if the ids can be kept.

Best,
Qing


-------------------------------------------------

Qing Luo, PhD student
Biomedicum B5
Dept. Physiology and Pharmacology
Karolinska Institutet
SE-17176 Stockholm
Sweden
Phone: +46 (0)704028006

**Comment by fork16** [comment]
@junchaoshi 
Hi Junchao,
pirbase provides version 3.0 now, with more piRNAs and unique IDs; If this ID is used to anno, the software will analyze piRNA very well.

**Comment by junchaoshi** [comment]
Hi,

It is possible to use the updated pirbase as a reference. You may use parameter -w [pirbase file] with out .fasta suffix as an input. The piRNA ID information is contained under bowtie format in the intermediate [_processed] folder if parameter -k is applied. However, the id information would not be included in the final output since we are still concerning if it makes sense to annotate a single piRNA. Hope the information helps. 

Junchao
