### ISSUE TITLE
can we merge the similar sequences when processing the smallRNA data

### ISSUE THREAD

**Issue by sunhaifeng123** [junchaoshi/sports1.1#29]
Hi, Junchao,

I got the results from sports1.1, some similar sequences like:

AAAAAACATTAGACTGTGAATCTGACAACAGGAAATAAACCTCCT     42     30    232     53    296   24   46  104  197  229
AAAAAACATTAGACTGTGAATCTGACAACAGGAAATAAACCTCC      16      9     63     22    120   12   16   20   48   30
AAAAAACATTAGACTGTGAATCTGACAACAGGAAATAAACCTC       29      3     41     22     47    7    4    0   21   21

and my supervisor hope that I can **merge such three sequence to one** so that perfrom following differential analysis.

I don't know whether it's suitable here for smallRNA data process and I didn't find literatures with such a description.

Can you give me some ideas or suggestions?

Thank you very much in advance!

Best,
Haifeng Sun

Ph.D. candidata student from Nanjing Medical University, China

**Comment by junchaoshi** [comment]
Hi Haifeng,

It depends on the reason for merging these sequences. Are these sequences share similar functions? Some previous works (e.g., PMID: 23063653) have shown that some miRNAs with different length, although sharing the overlapping sequences, have distinct seed sequences and target specificity. Hope the information helps.

I have to close the issue since it's not related to the software. 

Best,
Junchao
