### ISSUE TITLE
no annotaion file output

### ISSUE THREAD

**Issue by xingchang-web** [junchaoshi/sports1.1#36]
Hi Junchao,
I used this command line to annotate small RNA(input file is fastq format):
sports.pl -i seq_address.txt -p 4 -g /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/genome/hg38/genome \
-m /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/miRBase/21/miRBase_21-hsa \
-r /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/rRNAdb/human_rRNA \
-t /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/GtRNAdb/hg19/hg19-tRNAs \
-w /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/piRBase/piR_human \
-e /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/Ensembl/release-89/Homo_sapiens.GRCh38.ncrna \
-f /BIGDATA2/sysu_hshwang_1/soft/database/Homo_sapiens/Rfam/12.3/Rfam-12.3-human \
-o /BIGDATA2/sysu_hshwang_1/sports/output
the output file is follow:
![image](https://github.com/junchaoshi/sports1.1/assets/67858280/6bd6d83c-0ba7-41e6-a315-9389fc798557)

There is no error in the log file:
![image](https://github.com/junchaoshi/sports1.1/assets/67858280/cb1b8bef-2643-4da6-a243-54d445303531)

**Comment by junchaoshi** [comment]
Hi,

May I have the headline of the .fq file?

Junchao

**Comment by xingchang-web** [comment]
The headline of input .fq file as follow:
![image](https://github.com/junchaoshi/sports1.1/assets/67858280/2ea4a38f-13cb-4186-931a-1299255b9635)

**Comment by junchaoshi** [comment]
Hi, 

The 5' and 3' adaptors need to be removed using the -a  -x <str> -y <str> parameters in SPORTS.

Best,
Junchao

**Comment by xingchang-web** [comment]
Hi Junchao,
Thanks for your answer. Can i use sports to annotate tRF for miRNA-seq in TCGA?
Best,
xingchang

**Comment by junchaoshi** [comment]
Hi Xingchang,

Yes, you can! However, it's worth noting that traditional small RNA-seq methods have limitations when it comes to detecting tsRNAs due to the obscurity of RNA modifications (I have screened the data in TCGA before). We highly recommend reading our research papers for more in-depth information on this subject:
https://www.nature.com/articles/s41556-021-00652-7 and https://www.nature.com/articles/s41556-022-00880-5. 

Best,
Junchao
